language: php

php:
- 5.4
- 5.5
- 5.6
- hhvm

before_script:
- composer install
- composer require satooshi/php-coveralls:~0.6 --dev

after_script:
  - php vendor/bin/coveralls

notifications:
  email: false
